apiVersion: v1
kind: ConfigMap
metadata:
  name: hyperopt-config
  namespace: hyperopt-production
  labels:
    app: hyperopt-platform
    component: config
    environment: production
data:
  # Application Configuration
  ENVIRONMENT: "production"
  LOG_LEVEL: "INFO"
  API_HOST: "0.0.0.0"
  API_PORT: "8000"
  DEBUG: "false"
  
  # Database Configuration
  DATABASE_HOST: "postgres-service"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "hyperopt_prod"
  DATABASE_USER: "hyperopt"
  
  # Redis Configuration
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  
  # Celery Configuration
  CELERY_BROKER_URL: "redis://redis-service:6379/0"
  CELERY_RESULT_BACKEND: "redis://redis-service:6379/0"
  
  # Worker Configuration
  WORKER_CONCURRENCY: "4"
  WORKER_PREFETCH_MULTIPLIER: "1"
  WORKER_MAX_TASKS_PER_CHILD: "100"
  OPTIMIZATION_TIMEOUT: "3600"
  MAX_MEMORY_PER_WORKER: "4GB"
  
  # Scheduler Configuration
  SCHEDULER_INTERVAL: "60"
  CLEANUP_INTERVAL: "3600"
  MAX_TASK_RETRIES: "3"
  TASK_TIMEOUT: "7200"
  
  # Performance Configuration
  MAX_CONCURRENT_OPTIMIZATIONS: "10"
  CACHE_TTL: "3600"
  SESSION_TIMEOUT: "1800"
  REQUEST_TIMEOUT: "300"
  
  # Security Configuration
  CORS_ORIGINS: "https://app.hyperopt.company,https://admin.hyperopt.company"
  TRUSTED_HOSTS: "api.hyperopt.company,*.hyperopt.company"
  RATE_LIMIT_PER_MINUTE: "1000"
  
  # Monitoring Configuration
  METRICS_ENABLED: "true"
  METRICS_PORT: "9090"
  HEALTH_CHECK_INTERVAL: "30"
  
  # File Storage Configuration
  UPLOAD_MAX_SIZE: "100MB"
  RESULTS_RETENTION_DAYS: "90"
  LOGS_RETENTION_DAYS: "30"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hyperopt-config-staging
  namespace: hyperopt-staging
  labels:
    app: hyperopt-platform
    component: config
    environment: staging
data:
  # Application Configuration
  ENVIRONMENT: "staging"
  LOG_LEVEL: "DEBUG"
  API_HOST: "0.0.0.0"
  API_PORT: "8000"
  DEBUG: "true"
  
  # Database Configuration
  DATABASE_HOST: "postgres-service"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "hyperopt_staging"
  DATABASE_USER: "hyperopt"
  
  # Redis Configuration
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  
  # Celery Configuration
  CELERY_BROKER_URL: "redis://redis-service:6379/0"
  CELERY_RESULT_BACKEND: "redis://redis-service:6379/0"
  
  # Worker Configuration
  WORKER_CONCURRENCY: "2"
  WORKER_PREFETCH_MULTIPLIER: "1"
  WORKER_MAX_TASKS_PER_CHILD: "50"
  OPTIMIZATION_TIMEOUT: "1800"
  MAX_MEMORY_PER_WORKER: "2GB"
  
  # Scheduler Configuration
  SCHEDULER_INTERVAL: "60"
  CLEANUP_INTERVAL: "1800"
  MAX_TASK_RETRIES: "3"
  TASK_TIMEOUT: "3600"
  
  # Performance Configuration
  MAX_CONCURRENT_OPTIMIZATIONS: "5"
  CACHE_TTL: "1800"
  SESSION_TIMEOUT: "900"
  REQUEST_TIMEOUT: "300"
  
  # Security Configuration
  CORS_ORIGINS: "https://staging.hyperopt.company"
  TRUSTED_HOSTS: "staging.hyperopt.company,*.staging.hyperopt.company"
  RATE_LIMIT_PER_MINUTE: "500"
  
  # Monitoring Configuration
  METRICS_ENABLED: "true"
  METRICS_PORT: "9090"
  HEALTH_CHECK_INTERVAL: "30"
  
  # File Storage Configuration
  UPLOAD_MAX_SIZE: "50MB"
  RESULTS_RETENTION_DAYS: "30"
  LOGS_RETENTION_DAYS: "7" 