apiVersion: v1
kind: Secret
metadata:
  name: hyperopt-secrets
  namespace: hyperopt-production
  labels:
    app: hyperopt-platform
    component: secrets
    environment: production
type: Opaque
data:
  # NOTE: These values are base64 encoded placeholders
  # In production, use sealed-secrets, external-secrets, or vault integration
  
  # Database Secrets
  DATABASE_PASSWORD: cGxlYXNlLWNoYW5nZS1pbi1wcm9kdWN0aW9u  # please-change-in-production
  
  # Redis Secrets
  REDIS_PASSWORD: cGxlYXNlLWNoYW5nZS1pbi1wcm9kdWN0aW9u  # please-change-in-production
  
  # Application Secrets
  SECRET_KEY: c3VwZXItc2VjdXJlLWtleS1jaGFuZ2UtaW4tcHJvZHVjdGlvbi1lbnZpcm9ubWVudA==  # super-secure-key-change-in-production-environment
  JWT_SECRET_KEY: and0LXNlY3JldC1rZXktY2hhbmdlLWluLXByb2R1Y3Rpb24=  # jwt-secret-key-change-in-production
  
  # API Keys (External Services)
  ANTHROPIC_API_KEY: ""  # Base64 encoded Anthropic API key
  OPENAI_API_KEY: ""     # Base64 encoded OpenAI API key
  PERPLEXITY_API_KEY: "" # Base64 encoded Perplexity API key
  GOOGLE_API_KEY: ""     # Base64 encoded Google API key
  
  # Third-party Integration Secrets
  TRADINGVIEW_WEBHOOK_SECRET: ""  # Base64 encoded TradingView webhook secret
  SLACK_WEBHOOK_URL: ""           # Base64 encoded Slack webhook URL
  SENTRY_DSN: ""                  # Base64 encoded Sentry DSN
  
  # Email/SMTP Configuration
  SMTP_PASSWORD: ""         # Base64 encoded SMTP password
  EMAIL_HOST_PASSWORD: ""   # Base64 encoded email host password
  
  # Object Storage Secrets
  AWS_ACCESS_KEY_ID: ""     # Base64 encoded AWS access key
  AWS_SECRET_ACCESS_KEY: "" # Base64 encoded AWS secret key
  
  # Monitoring Secrets
  GRAFANA_ADMIN_PASSWORD: Z3JhZmFuYS1hZG1pbi1wYXNzd29yZC0xMjM=  # grafana-admin-password-123

---
apiVersion: v1
kind: Secret
metadata:
  name: hyperopt-secrets-staging
  namespace: hyperopt-staging
  labels:
    app: hyperopt-platform
    component: secrets
    environment: staging
type: Opaque
data:
  # Staging Environment Secrets (Less sensitive)
  
  # Database Secrets
  DATABASE_PASSWORD: c3RhZ2luZy1wYXNzd29yZC0xMjM=  # staging-password-123
  
  # Redis Secrets
  REDIS_PASSWORD: c3RhZ2luZy1yZWRpcy0xMjM=  # staging-redis-123
  
  # Application Secrets
  SECRET_KEY: c3RhZ2luZy1zZWNyZXQta2V5LWZvci10ZXN0aW5n  # staging-secret-key-for-testing
  JWT_SECRET_KEY: c3RhZ2luZy1qd3Qta2V5  # staging-jwt-key
  
  # API Keys (Test/Development Keys)
  ANTHROPIC_API_KEY: ""  # Base64 encoded test Anthropic API key
  OPENAI_API_KEY: ""     # Base64 encoded test OpenAI API key
  PERPLEXITY_API_KEY: "" # Base64 encoded test Perplexity API key
  
  # Development Integration Secrets
  SLACK_WEBHOOK_URL: ""  # Base64 encoded staging Slack webhook
  SENTRY_DSN: ""         # Base64 encoded staging Sentry DSN
  
  # Monitoring Secrets
  GRAFANA_ADMIN_PASSWORD: c3RhZ2luZy1ncmFmYW5hLTEyMw==  # staging-grafana-123

---
# TLS Secret Template (Replace with actual certificates)
apiVersion: v1
kind: Secret
metadata:
  name: hyperopt-tls
  namespace: hyperopt-production
  labels:
    app: hyperopt-platform
    component: tls
    environment: production
type: kubernetes.io/tls
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t  # Base64 encoded certificate
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0t  # Base64 encoded private key

---
apiVersion: v1
kind: Secret
metadata:
  name: hyperopt-tls-staging
  namespace: hyperopt-staging
  labels:
    app: hyperopt-platform
    component: tls
    environment: staging
type: kubernetes.io/tls
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t  # Base64 encoded staging certificate
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0t  # Base64 encoded staging private key 