disable_existing_loggers: false
formatters:
  detailed:
    format: '%(asctime)s [%(levelname)s] %(name)s:%(lineno)d: %(message)s'
  json:
    format: '{"timestamp": "%(asctime)s", "level": "%(levelname)s", "logger": "%(name)s",
      "message": "%(message)s", "module": "%(module)s", "function": "%(funcName)s",
      "line": %(lineno)d}'
  standard:
    format: '%(asctime)s [%(levelname)s] %(name)s: %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    formatter: standard
    level: INFO
    stream: ext://sys.stdout
  error_file:
    backupCount: 5
    class: logging.handlers.RotatingFileHandler
    filename: /Users/jbyrd/Documents/GitHub/hyperopt strat/logs/errors.log
    formatter: detailed
    level: ERROR
    maxBytes: 10485760
  info_file:
    backupCount: 5
    class: logging.handlers.RotatingFileHandler
    filename: /Users/jbyrd/Documents/GitHub/hyperopt strat/logs/application.log
    formatter: detailed
    level: INFO
    maxBytes: 10485760
  performance_file:
    backupCount: 3
    class: logging.handlers.RotatingFileHandler
    filename: /Users/jbyrd/Documents/GitHub/hyperopt strat/logs/performance.log
    formatter: json
    level: INFO
    maxBytes: 10485760
loggers:
  ? ''
  : handlers:
    - console
    - info_file
    - error_file
    level: INFO
  performance:
    handlers:
    - performance_file
    level: INFO
    propagate: false
  trading_strategies:
    handlers:
    - info_file
    - error_file
    level: DEBUG
    propagate: false
version: 1
